[package]
name = "yerpc"
version = "0.6.2"
edition = "2021"
license = "Apache-2.0/MIT"
repository = "https://github.com/deltachat/yerpc"
description = "Ergonomic JSON-RPC library for async Rust with Axum support"
authors = [
  "Franz Heinzmann <Frando>",
  "Contributors to yerpc"
]

[[bin]]
name = "generate-base-types"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yerpc_derive = { path  = "../yerpc-derive", version = "0.6" }
async-trait = "0.1.53"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
log = "0.4.16"
futures = "0.3.21"
futures-util = "0.3.21"
async-channel = "1.6.1"
async-lock = "3.4.0"

# type generating dependencies
typescript-type-def = { version = "0.5.3", features = ["json_value"] }
schemars = { version = "0.8.11", optional = true }

# optional dependencies
anyhow = { version = "1.0.57", optional = true }
axum = { version = "0.7.1", features = ["ws"], optional = true }
tokio-tungstenite = { version = "0.20", optional = true }
tokio = { version = "1.19.2", features = ["rt", "macros"], optional = true }
tracing = { version = "0.1.35", optional = true }

[features]
anyhow_expose = ["anyhow"]
support-axum = ["axum", "tokio", "anyhow", "tracing"]
support-tungstenite = ["tokio", "tokio-tungstenite", "anyhow"]
openrpc = ["schemars", "yerpc_derive/openrpc"]

[dev-dependencies]
anyhow = "1.0.57"
axum = { version = "0.7.1", features = ["ws"] }
tokio-tungstenite = { version = "0.20" }
tokio = { version = "1.19.2", features = ["rt", "macros"] }
url = "2.2.2"
